:sparkles: [Feature/post-37] 게시글 기능 구현
selab-hs/selab pull request #50
Opened 2022-01-25 08:40 UTC by leeheefull

## 💡 개요 

- resolved #37 

## 📑 작업 사항 

## ✒️ 코드 리뷰 요청 사항

## ✔️ 코드 리뷰 반영 사항

2022-01-25 12:25 UTC, DongGeon0908 requested changes
고생하셨습니다 희찬님!

2022-01-25 12:25 UTC, DongGeon0908 commented on src/main/java/kr/ac/hs/selab/post/domain/Post.java
> +        this.title = this.title + Constants.TITLE_SEPARATOR + UUID.randomUUID();
UUID를 사용하신 이유는 delete flag가 나가고 나서, title에 대한 중복을 처리하기 위함일까요??

어떤 이유로 UUID를 사용하신 걸까요?

2022-01-25 12:25 UTC, DongGeon0908 commented on src/main/java/kr/ac/hs/selab/common/utils/Constants.java
>  }
해당 클래스가 필요한 이유가 무엇일까요?

상수를 제어하기 위한 용도라면, 클래스로 관리할 필요가 있을지 궁금합니다!

2022-01-25 14:16 UTC, leeheefull commented on src/main/java/kr/ac/hs/selab/post/domain/Post.java
> +        this.title = this.title + Constants.TITLE_SEPARATOR + UUID.randomUUID();
@DongGeon0908 
삭제가 되더라도 `title`에 대한 정보가 필요할 것이라고 생각되어 두었습니다.
`UUID`를 넣은 이유는 삭제된 `title` 중에서도 중복이 일어날 수 있기 때문입니다.

2022-01-25 14:17 UTC, leeheefull commented on src/main/java/kr/ac/hs/selab/common/utils/Constants.java
>  }
@DongGeon0908 

두 변수가 여러 곳에서 사용되기 때문에 만들었습니다.

2022-01-25 16:46 UTC, DongGeon0908 commented on src/main/java/kr/ac/hs/selab/post/domain/Post.java
> +        this.title = this.title + Constants.TITLE_SEPARATOR + UUID.randomUUID();
delete flag가 없는 것에서 조회를 진행하면 되지 않나요??
UUID를 사용하게 되면, 불필요한 데이터가 쌓이는게 아닐까 생각됩니다!

2022-01-26 01:48 UTC, leeheefull commented on src/main/java/kr/ac/hs/selab/post/domain/Post.java
> +        this.title = this.title + Constants.TITLE_SEPARATOR + UUID.randomUUID();
@DongGeon0908 

조회를 할 때는 문제가 되지 않습니다. 삽입이나 수정을 할 때, 같은 제목의 게시판 중복이 일어납니다.
그럴 경우 직접 중복 처리를 해줘야하는데, 코드 양이 많아진다고 생각이 들었습니다.
그래서 `unique`처리를 했고, 유니크 처리를 하게 된다면 위에서 말씀 드린 것처럼 삭제된 것중에서도 중복된 게시판이 존재할 수 있기 때문에, UUID값을 넣어 주었습니다.

2022-01-26 02:14 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/domain/Post.java
> +        this.title = this.title + Constants.TITLE_SEPARATOR + UUID.randomUUID();
`TITLE_SEPRATOR` X
`HYPHEN` O

2022-01-26 02:18 UTC, jeonyeonbin approved these changes
고생하셨습니다 👍

2022-01-26 14:18 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/common/utils/Constants.java
> +    public final boolean DELETED = true;
불필요한 변수 상수인걸로 보입니다.

2022-01-26 14:21 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
> +    List<Post> findByBoard(@Param("board") Board board);
query문 없이도 동작할텐데 굳이 쿼리를 넣어야될까요?

2022-01-26 14:21 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
> +                                                 @RequestBody PostRequest request) {
`@Valid`?

2022-01-26 14:22 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
> +        return ResponseTemplate.ok(ResponseMessage.POST_FIND_SUCCESS, response);
POST_UPDATE_SUCCESS ?

2022-01-26 14:24 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/application/PostService.java
> +    private Member getMember(String memberEmail) {
memberService에 있어야되지않을까요?

2022-01-26 14:24 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/application/PostService.java
> +        return boardRepository.find(boardId, Constants.NOT_DELETED)
BoardService에 있어야되지않을까요?

2022-01-26 14:24 UTC, jeonyeonbin commented on src/main/java/kr/ac/hs/selab/post/application/PostService.java
> +public class PostService {
PostFacade?

2022-01-27 03:28 UTC, merged

2022-01-28 08:16 UTC, leeheefull commented on src/main/java/kr/ac/hs/selab/post/application/PostService.java
> +public class PostService {
퍼사드 레이어를 적용하여 구현해보겠습니다!